# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ebe6d6c90a6ffe772e86ccc85300ed704d9ca6f46a4e5778c2d559cc50b3cfe73bf36a4d6ae288da3e28d7a7ca7b2dbe43d36c2196e181211805db864c2ce57

test:
  secret_key_base: a099c53279eb727f72d14dafe8517d6cdc58e517a20471f0a321b225f67cd85b15f6fa17ae18f905fa6ed7fd4be1e9c33c3297fa73fa6fccf908d7f983a47b15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
